### ISSUE TITLE
SubscribeHandler not working when NonVerbose is true

### ISSUE THREAD

**Issue by kevin96666** [recws-org/recws#22]
Hello,

I don't understand why the SubscribeHandler is executed only when getNonVerbose is false.
Is mean that we can't use this feature in NonVerbose mode. Makes no sense for me.
Is there any reason ?

**Comment by loeffel-io** [comment]
Hey @kevin96666 

You are absolutely right! The keepAlive system is also not working with the nonVerbose mode. 
Would love to see a PR for this!

**Comment by kevin96666** [comment]
Hey @loeffel-io 

Just did a PR.

**Comment by loeffel-io** [comment]
Thanks @kevin96666 

Now available in v1.2.0
