### ISSUE TITLE
KeepAliveInterval should be less than KeepAliveTimeout

### ISSUE THREAD

**Issue by qingshan** [recws-org/recws#24]
KeepAliveInterval should be less than KeepAliveTimeout (ideally less than 1/2). so the code should be change from:
https://github.com/recws-org/recws/blob/c08788cb069aee755702bfd577d34b066621f486/recws.go#L361

to:
` ticker            = time.NewTicker(rc.getKeepAliveTimeout() / 2) `

This will solve occasionally keep alive timeout problem.

**Comment by loeffel-io** [comment]
Thanks @qingshan for the issue! 

Could you please give me some more informations - there is no "KeepAliveInterval"

**Comment by qingshan** [comment]
The argument of time.NewTicker is actually the concept of KeepAliveInterval.
```
keepAliveInterval := rc.getKeepAliveTimeout() / 2
ticker = time.NewTicker(keepAliveInterval)
```

Because in this piece of code:
```
if err := rc.writeControlPingMessage(); err != nil {
	log.Println(err)
}
<-ticker.C
if time.Since(keepAliveResponse.getLastResponse()) > rc.getKeepAliveTimeout() {
	rc.CloseAndReconnect()
	return
}
```

If `<-ticker.C` wait the same amount time as KeepAliveTimeout, the result of `time.Since(keepAliveResponse.getLastResponse()) > rc.getKeepAliveTimeout()` is easily to be true.

**Comment by loeffel-io** [comment]
I think i understand the issue. 

What about simply change 

`if time.Since(keepAliveResponse.getLastResponse()) > rc.getKeepAliveTimeout()`

to 

`if time.Since(keepAliveResponse.getLastResponse()) >= rc.getKeepAliveTimeout()`

**Comment by loeffel-io** [comment]
ping @qingshan

**Comment by qingshan** [comment]
The original code should be OK. I had a mistake, because I was thinking that What if the pong message is handled before `<-ticker.C` is executed.
