### ISSUE TITLE
How do you send a message on reconnect?

### ISSUE THREAD

**Issue by pacedavis** [recws-org/recws#26]
I need to send a login message when the connection is reestablished.  How do I do this?

**Comment by loeffel-io** [comment]
You can just use the subscribeHandler

**Comment by pacedavis** [comment]
Thank you Lucas for the very quick reply!  Can you give me a quick example of how I do that?  I see hasSubscribeHandler, not sure where I capture events for subscribeHandler.  Please excuse my ignorance.

**Comment by loeffel-io** [comment]
You can just set the SubscribeHandler as field: https://github.com/recws-org/recws/blob/master/recws.go#L43 

Let me know if this does not help - then i will create a quick example for you tomorrow

**Comment by loeffel-io** [comment]
Should look like this: 

```go
&recws.RecConn{
			RecIntvlMax:      10 * time.Minute,
			SubscribeHandler: func() error{ // send your login message here },
			KeepAliveTimeout: 10 * time.Second,
		},
```

**Comment by pacedavis** [comment]
Awesome.  Thank you so much!
