### ISSUE TITLE
v1.3.0 module broken due to duplicate makefile

### ISSUE THREAD

**Issue by anitgandhi** [recws-org/recws#36]
When trying to get the new v1.3.0:

```
go: github.com/recws-org/recws@v1.3.0: verifying go.mod: github.com/recws-org/recws@v1.3.0/go.mod: reading https://sum.golang.org/lookup/github.com/recws-org/recws@v1.3.0: 410 Gone
        server response: not found: create zip: makefile: case-insensitive file name collision: "Makefile" and "makefile"
```

I believe this is due to upstream issue : https://github.com/golang/go/issues/33778

Can you please collapse the 2 Makefiles into 1 and release a v1.3.1?

Thanks!

**Comment by anitgandhi** [comment]
Also please consider adding the following lines to `go.mod`, since both versions are broken:

```
retract v1.2.2
retract v1.3.0
```

**Comment by loeffel-io** [comment]
Its crazy, does 2 makefiles did not exists on my machine - will do that now, thanks for the info 👍

**Comment by loeffel-io** [comment]
<img width="656" alt="Bildschirmfoto 2021-03-17 um 10 43 41" src="https://user-images.githubusercontent.com/12670730/111447377-abb4a780-870d-11eb-89d2-540124dc55d1.png">
