### ISSUE TITLE
ignore TLS certificate error (self signed)

### ISSUE THREAD

**Issue by franck34** [recws-org/recws#37]
Hi,

Is there a way for ignoring SSL/TLS Certificats error ? My websocket dev server use TLS with a self signed certificate.

Note that after retrying after 2 seconds, recws enter into a loop for 2 seconds before closing ws, see #38

**Comment by loeffel-io** [comment]
There is the `TLSClientConfig` for this

**Comment by franck34** [comment]
For memory:

```
        ws := recws.RecConn{
		KeepAliveTimeout: 10 * time.Second,
	}

	ws.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
```
